compatible: "cirque,pinnacle"
include: spi-device.yaml

properties:
  dr-gpios:
    type: phandle-array
    required: true
    description: "Data Ready (Interrupt) GPIO"
  sensitivity:
    type: string
    default: "4x"
    enum: ["1x", "2x", "3x", "4x"]
