description: "Cirque Pinnacle Trackpad"
compatible: "cirque,pinnacle"
include: spi-device.yaml

properties:
  dr-gpios:
    type: phandle-array
    required: true
    description: "Data Ready Interrupt GPIO"
