parse_config:
  columns: 10              # Zwingt den Parser auf 3x5+3 (10 Spalten)
  check_side_key_usage: true
  raw_binding_map:
    # --- LAYER KEYS & ROT-FIX ---
    "&lt 1 TAB": {t: "⇥", h: "Lower", type: "held"}
    "&lt 1 RET": {t: "↵", h: "Lower", type: "held"}
    "&lt 2 ESC": {t: "ESC", h: "Raise", type: "held"}
    "&lt_hp 2 SPACE": {t: "␣", h: "Raise", type: "held"}
    "&lt_hp 3 BSPC": {t: "⌫", h: "Adjust", type: "held"}
    "&mo 1": {t: "Lower", type: "held"}
    "&mo 2": {t: "Raise", type: "held"}
    "&mo 3": {t: "Adjust", type: "held"}
    "&kp HOME": {t: "⤒ Pos1", type: "held"}  # h: macht die Taste rot
    "&kp END": {t: "⤓ End", type: "held"}    # h: macht die Taste rot

    # --- DEUTSCHE TASTEN ---
    "&kp N1": {t: "1", s: "!"}
    "&kp N2": {t: "2", s: "\""}
    "&kp N3": {t: "3", s: "§"}
    "&kp N4": {t: "4", s: "$"}
    "&kp N5": {t: "5", s: "%"}
    "&kp N6": {t: "6", s: "&"}
    "&kp N7": {t: "7", s: "/"}
    "&kp N8": {t: "8", s: "("}
    "&kp N9": {t: "9", s: ")"}
    "&kp N0": {t: "0", s: "="}
    "&kp MINUS": {t: "ß", s: "?"}
    "&kp SEMI": "Ö"
    "&kp SQT": "Ä"
    "&kp LBKT": "Ü"
    "&kp RA(Q)": "@"
    "&kp RA(E)": "€"
    "&kp NON_US_BSLH": {t: "<", s: ">"}
    "&kp SLASH": {t: "-", s: "_"}
    "&kp RBKT": {t: "+", s: "*"}

draw_config:
  dark_mode: true
  n_columns: 1
  append_style: |
    svg { background-color: #1a1b26; }
    rect.key { fill: #24283b; stroke: #414868; }
    text { fill: #c0caf5; }
    rect.held { fill: #f7768e; } /* Das Rot für Home, End und Layer */
