
parse_config:
  raw_binding_map:
    "&trans": " "           # Macht &trans komplett leer/unsichtbar
    "&none": " "            # Macht &none komplett leer/unsichtbar
    
    # --- LAYER KEYS (ROT) ---
    "&lt 1 TAB": {t: "⇥", h: "Lower"}
    "&lt 1 RET": {t: "↵", h: "Lower"}
    "&lt 2 ESC": {t: "ESC", h: "Raise"}
    "&lt_hp 2 SPACE": {t: "␣", h: "Raise"}
    "&lt_hp 3 BSPC": {t: "⌫", h: "Adjust"}
    "&mo 1": {t: "Lower", type: "held"}
    "&mo 2": {t: "Raise", type: "held"}
    "&mo 3": {t: "Adjust", type: "held"}
    "&kp HOME": {t: "⤒ Pos1", type: "held"}
    "&kp END": {t: "⤓ End", type: "held"}
    "&kp LC(LS(ESC))": {t: "Task Mgr", type: "held"}
    "&nbsp": {t: "&nbsp", type: "held"}
    "&kp F12": {t: " ", type: "held"}
    "&kp F13": {t: " ", type: "held"}
    "&kp F14": {t: " ", type: "ghost"}
    "&kp F15": {t: " ", type: "remove_me"}
    "&f10_ghost": {t: "F10", type: "ghost"} 
    "&kp F11": "RGB"

    # --- MATH CODES (NUMPAD) ---
    "&kp KP_PLUS": "+"
    "&kp KP_MINUS": "-"
    "&kp KP_MULTIPLY": "*"
    "&kp KP_DIVIDE": "/"
    "&kp KP_EQUAL": "="
    
    # --- SYMBOLE & NAVIGATION ---
    "&kp BSPC": "⌫"
    "&kp DEL": "⌦"
    "&kp LGUI": "$$mdi:microsoft-windows-classic$$"
    "&kp GRAVE": {t: "^", s: "°"}
    "&kp PLUS": "`"

    # --- ZAHLEN & UMLAUTE ---
    "&kp N1": {t: "1", s: "!"}
    "&kp N2": {t: "2", s: "\""}
    "&kp N3": {t: "3", s: "§"}
    "&kp N4": {t: "4", s: "$"}
    "&kp N5": {t: "5", s: "%"}
    "&kp N6": {t: "6", s: "&"}
    "&kp N7": {t: "7", s: "/"}
    "&kp N8": {t: "8", s: "("}
    "&kp N9": {t: "9", s: ")"}
    "&kp N0": {t: "0", s: "="}
    "&kp MINUS": {t: "ß", s: "?"}
    "&kp SEMI": "Ö"
    "&kp SQT": "Ä"
    "&kp LBKT": "Ü"
    "&kp RA(N7)": "{"
    "&kp RA(N8)": "["
    "&kp RA(N9)": "]"
    "&kp RA(N0)": "}"
    "&kp RA(Q)": "@"
    "&kp RA(E)": "€"
    "&kp RA(M)": "µ"
    "&kp RA(MINUS)": "\\"
    "&kp RA(SQT)": "´"
    "&kp RA(NON_US_BSLH)": "|"
    "&kp RA(RBKT)": "~"
    "&kp RA(N2)": "²"
    "&kp RA(N3)": "³"
    "&kp NON_US_HASH": {t: "#", s: "'"}
    "&kp NON_US_BSLH": {t: "<", s: ">"}
    "&kp SLASH": {t: "-", s: "_"}
    "&kp RPAR": "="
    "&kp RBKT": {t: "+", s: "*"}
    "&kp Q": {t: "Q", s: "@"}
    "&kp E": {t: "E", s: "€"}
    "&kp M": {t: "M", s: "µ"}

    # --- SYSTEM & BT ---
    "&usb_on": {t: "ψ USB", s: "☀ ON"}
    "&bt_off": {t: "$$mdi:bluetooth$$", s: "☀ OFF"}
    "&bt BT_SEL 0": {t: "$$mdi:bluetooth$$", s: "⓵", h: "PC"}
    "&bt BT_SEL 1": {t: "$$mdi:bluetooth$$", s: "⓶", h: "S8"}
    "&bt BT_SEL 2": {t: "$$mdi:bluetooth$$", s: "⓷", h: "Zbook"}
    "&bt BT_SEL 3": {t: "$$mdi:bluetooth$$", s: "⓸"}
    "&bt BT_SEL 4": {t: "$$mdi:bluetooth$$", s: "⓹"}
    "&kp LA(F4)": {t: "✕", s: "Alt F4"}

    # --- SONSTIGES ---
    "&smiley": {t: "☻", type: "ghost"}
    "&durchmesser": "Ø"
    "&kp C_PREV": "⏮"
    "&kp C_NEXT": "⏭"
    "&kp C_PP": {t: "⏯", type: "ghost"}
    "&mkp LCLK": "🖱 LMB"
    "&mkp RCLK": "🖱 RMB"

    # --- MODIFIERS ---
    "&hrm_safe LCTRL D": {t: "D", h: "CTRL"}
    "&hrm_shift LSHIFT F": {t: "F", h: "Shift"}
    "&hrm_shift RSHIFT J": {t: "J", h: "Shift"}
    "&hrm_safe RCTRL K": {t: "K", h: "CTRL"}
    "&hrm_safe LALT X": {t: "X", h: "Alt"}
    "&hrm_safe RALT DOT": {t: ".", s: "AltGr"}
    
    # --- RGB UNTERBELEUCHTUNG ---
    "&rgb_ug RGB_TOG": {t: "$$mdi:lightbulb-on$$", s: "OnOff"}
    "&rgb_ug RGB_EFF": {t: "$$mdi:cosine-wave$$", s: "Mode"}
    "&rgb_ug RGB_EFR": {t: "$$mdi:cosine-wave$$", s: "Rev"}
    "&rgb_ug RGB_BRI": {t: "$$mdi:brightness-7$$", s: "Bri+"}
    "&rgb_ug RGB_BRD": {t: "$$mdi:brightness-4$$", s: "Bri-"}
    "&rgb_ug RGB_SAI": {t: "$$mdi:palette$$", s: "Sat+"}
    "&rgb_ug RGB_SAD": {t: "$$mdi:palette-outline$$", s: "Sat-"}
    "&rgb_ug RGB_HUI": {t: "$$mdi:palette-swatch$$", s: "Hue+"}
    "&rgb_ug RGB_HUD": {t: "$$mdi:palette-swatch-outline$$", s: "Hue-"}

    # --- BLUETOOTH & SYSTEM ---
    "&bt BT_CLR": {t: "$$mdi:bluetooth-off$$", s: "CLR", type: "ghost"}
    "&bt_off": {t: "$$mdi:bluetooth-off$$"}
    "&usb_on": "$$mdi:usb$$"
    "&kp LA(F4)": "✕"
    "&ext_power EP_TOG": "Pwr±"
    "&ext_power EP_ON": "Pwr+"

draw_config:
  dark_mode: true
  n_columns: 1
  width: 1200
