# --- MAUS & POINTING ---
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=n
CONFIG_ZMK_USB_BOOT=y

# --- ENCODER ---
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# --- VERBINDUNG ---
# Höhere Sendeleistung hilft gegen Funk-Aussetzer zwischen den Hälften
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- DISPLAY (nice!view) ---
# Da du es loswerden willst, lassen wir es auf Sparflamme mitlaufen, 
# damit der Build nicht wegen fehlender Display-Referenzen meckert.
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_NICE_VIEW_WIDGET_STATUS=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# --- BATTERIE ---
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y


# --- RGB LEDS (KOMPLETT AUS) ---
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
# Wir setzen das hier zur Sicherheit, damit kein Treiber geladen wird
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n

# Treiber für das nice!view (Sharp LS0XX)
CONFIG_SHARP_DISPLAY=y

# SPI aktivieren, da das Display darüber kommuniziert
CONFIG_SPI=y
