# Bluetooth aktivieren
CONFIG_ZMK_BLE=y

# Display explizit aus für die rechte Seite
CONFIG_ZMK_DISPLAY=n

# Maus-Support aktivieren
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

# SPI für das Trackpad
CONFIG_SPI=y
CONFIG_INPUT=y
