manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # Wir bleiben bei main, aber ohne das defekte LED-Modul
      import: app/west.yml
  self:
    path: config
