name: Vertical Display Success
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Wir lassen den Pfad weg, damit alles im Root landet

      - name: Manual Setup
        run: |
          # 1. ZMK manuell klonen
          git clone https://github.com/zmkfirmware/zmk.git zmk_workspace
          
          # 2. West initialisieren
          # Wir suchen die west.yml, egal wo sie sich versteckt hat
          WEST_YML_PATH=$(find . -name "west.yml" | head -n 1)
          echo "West.yml gefunden unter: $WEST_YML_PATH"
          
          cd zmk_workspace
          west init -l app/
          
          # 3. West Update
          west update
          west zephyr-export

      - name: Build Left
        run: |
          west build -s zmk_workspace/app -p -b nice_nano_v2 -- \
          -DSHIELD="splitkb_aurora_corne_left nice_view_adapter nice_view" \
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          cp build/zephyr/zmk.uf2 left.uf2

      - name: Build Right
        run: |
          west build -s zmk_workspace/app -p -b nice_nano_v2 -- \
          -DSHIELD="splitkb_aurora_corne_right" \
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          cp build/zephyr/zmk.uf2 right.uf2

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware-corne
          path: ./*.uf2
