name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & Build (ZMK Action)
        uses: zmkfirmware/zmk-build-action@v2
        with:
          repository: zmkfirmware/zmk
          branch: main
          # Hier definierst du nur das Board und das Shield
          board: nice_nano_v2
          shield: splitkb_aurora_corne_left nice_view_adapter nice_view
          # Dein Config-Ordner (wo deine Keymap/Overlays liegen)
          config_path: config
